namespace Net.Leksi.Edifact;

public enum ErrorKinds
{
    UNEXPECTED_SEGMENT,
    EXPECTED_ELEMENT_NOT_FOUND,
    EXPECTED_SUB_ELEMENT_NOT_FOUND,
    EXTRA_SUB_ELEMENT_FOUND,
    EXTRA_ELEMENT_FOUND,
    INCOMPLETE_SEGMENT,
    INVALID_FORMAT,
    FG_ID_MISMATCH,
    MESSAGE_ID_MISMATCH,
    NUMBER_OF_SEGMENTS_MISMATCH,
    NUMBER_OF_MESSAGES_MISMATCH,
    INTERCHANGE_ID_MISMATCH,
    UNKNOWN_SEGMENT,
    INCOMPLETE_ELEMENT,
    INVALID_ELEMENT_VALUE,
    INVALID_SUB_ELEMENT_VALUE,
};
